#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Overall title for pages.
title: "RevBayes"

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# Sites.
revbayes_site: "https://revbayes.github.io"

url: https://revbayes.github.io
baseurl: ""

plugins: ['jekyll/scholar']

include: [.nojekyll]
exclude:
- deploy.sh
- README.md
- Gemfile
- Gemfile.lock

empty_array: []

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      code_layout: default
  - scope:
      path: "tutorials"
    values:
      layout: tutorial
      code_layout: Rev
  - scope:
      path: "developer"
    values:
      layout: developer

scholar:
  bibliography_template: bib
  style: systematic-biology
  sort_by: author
  order: ascending

# Conversion
kramdown:
  syntax_highlighter: rouge

sass:
  sass_dir: assets/_scss
