#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Overall title for pages.
title: "RevBayes Tutorials"

# Contact email address.
email: willpett@iastate.edu

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: <USERNAME>/<PROJECT>

baseurl: "/revbayes_tutorials"

# Sites.
revbayes_site: "https://revbayes.github.io"

# Specify that things in the tutorials collection should be output.
# collections:
#   tutorials:
#     output: true
#     permalink: /tutorials/:name:output_ext
#   extras:
#     output: true

# # Set the default layout for things in the tutorials collection.
# defaults:
#   - values:
#       root: ..
#   - scope:
#       path: ""
#     values:
#       layout: tutorial

# Turn off built-in syntax highlighting.
highlighter: false

plugins: ['jekyll/scholar']

include: [.nojekyll]