#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Overall title for pages.
title: "RevBayes"

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# Sites.
revbayes_site: "https://revbayes.github.io"

url: https://revbayes.github.io
baseurl: "/revbayes-site"

plugins: ['jekyll/scholar']

include: [.nojekyll]

empty_array: []

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      code_layout: default
  - scope:
      path: "tutorials"
    values:
      layout: tutorial
      code_layout: Rev
  - scope:
      path: "developer"
    values:
      layout: developer

scholar:
  bibliography_template: bib
  style: systematic-biology

# Conversion
kramdown:
  syntax_highlighter: rouge
