#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Overall title for pages.
title: "RevBayes Tutorials"

# Contact email address.
email: willpett@iastate.edu

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: <USERNAME>/<PROJECT>

baseurl: "/revbayes_tutorials"

# Sites.
revbayes_site: "https://revbayes.github.io"

plugins: ['jekyll/scholar']

include: [.nojekyll]

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "tutorials"
    values:
      layout: tutorial
  - scope:
      path: "developer"
    values:
      layout: developer
  - scope:
      layout: tutorial
    values:
      code_layout: Rev
  - scope:
      layout: developer
    values:
      code_layout: cpp

scholar:
  bibliography_template: bib
  style: systematic-biology
  locale: en

# Conversion
kramdown:
  syntax_highlighter: rouge
